apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment
        image: 22251a1257it258/assignment:latest
        ports:
        - containerPort: 5000
